fix yml syntax

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -2,72 +2,73 @@ name: main
 on: [push]
 
 jobs:
-  runs-on: "ubuntu-latest"
-  steps:
-  - uses: actions/checkout@v2
+  build-and-test:
+    runs-on: "ubuntu-latest"
+    steps:
+    - uses: actions/checkout@v2
 
 
-  # Set up conda environment for subsequent jobs
-  - name: build env
-    run: |
-      eval "$(conda shell.bash hook)"
-      conda create -p ./env --file requirements.txt --channel conda-forge
+    # Set up conda environment for subsequent jobs
+    - name: build env
+      run: |
+        eval "$(conda shell.bash hook)"
+        conda create -p ./env --file requirements.txt --channel conda-forge
 
 
-  # Run doctests if you have them configured
-  - name: run doctests
-    run: |
-      eval "$(conda shell.bash hook)"
-      conda activate ./env
-      (cd docs && make doctest)
+    # Run doctests if you have them configured
+    - name: run doctests
+      run: |
+        eval "$(conda shell.bash hook)"
+        conda activate ./env
+        (cd docs && make doctest)
 
 
-  # Build docs and commit them to gh-pages branch
-  - name: build docs
-    run: |
+    # Build docs and commit them to gh-pages branch
+    - name: build docs
+      run: |
 
-      # Activate env and build docs
-      eval "$(conda shell.bash hook)"
-      conda activate ./env
-      (cd docs && make html)
+        # Activate env and build docs
+        eval "$(conda shell.bash hook)"
+        conda activate ./env
+        (cd docs && make html)
 
-      # Clone just the gh-pages branch to a temp dir.
-      git clone \
-        --single-branch \
-        --branch gh-pages "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY" \
-        /tmp/docs
+        # Clone just the gh-pages branch to a temp dir.
+        git clone \
+          --single-branch \
+          --branch gh-pages "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY" \
+          /tmp/docs
 
-      # Clean out that temp dir, we're about to move our just-built docs there
-      rm -rf /tmp/docs/*
-      cp -r docs/build/html/* /tmp/docs
+        # Clean out that temp dir, we're about to move our just-built docs there
+        rm -rf /tmp/docs/*
+        cp -r docs/build/html/* /tmp/docs
 
-      # GitHub defaults to assuming Jekyll pages, the presence of this file
-      # makes Sphinx work well
-      touch /tmp/docs/.nojekyll
+        # GitHub defaults to assuming Jekyll pages, the presence of this file
+        # makes Sphinx work well
+        touch /tmp/docs/.nojekyll
 
-      # Commit our changes to the gh-pages branch. Note that they will not be
-      # pushed unless we're on the master branch.
-      cd /tmp/docs
-      git config --global user.email "action@github.com"
-      git config --global user.name "GitHub Action"
-      git add .
+        # Commit our changes to the gh-pages branch. Note that they will not be
+        # pushed unless we're on the master branch.
+        cd /tmp/docs
+        git config --global user.email "action@github.com"
+        git config --global user.name "GitHub Action"
+        git add .
 
-      # git commit exits nonzero if nothing to commit, but we don't want to
-      # consider that an error so we ignore it.
-      git commit -m 'update docs' -a || true
-
-
-  # Upload the built docs as an artifact for inspection (even on PRs)
-  - name: push artifact
-    uses: actions/upload-artifact@v2
-    with:
-      name: docs
-      path: /tmp/docs
+        # git commit exits nonzero if nothing to commit, but we don't want to
+        # consider that an error so we ignore it.
+        git commit -m 'update docs' -a || true
 
 
-  # Push docs to gh-pages but ONLY if this test is running on master branch
-  - name: push docs to gh-pages branch
-    if: ${{ (github.ref == 'refs/heads/main') }}
-    run: |
-      cd /tmp/docs
-      git push "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY" gh-pages
+    # Upload the built docs as an artifact for inspection (even on PRs)
+    - name: push artifact
+      uses: actions/upload-artifact@v2
+      with:
+        name: docs
+        path: /tmp/docs
+
+
+    # Push docs to gh-pages but ONLY if this test is running on master branch
+    - name: push docs to gh-pages branch
+      if: ${{ (github.ref == 'refs/heads/main') }}
+      run: |
+        cd /tmp/docs
+        git push "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY" gh-pages
